In [ ]:
from sklearn.model_selection import GroupKFold
from sklearn.linear_model import SGDClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import make_pipeline
from sklearn import svm
from scipy import signal
import tensorflow as tf
from tensorflow.keras.models import Sequential
from keras.layers.core import Dense, Dropout
from tensorflow.keras.layers import LSTM

import matplotlib.pyplot as plt
import scipy.io as sio

!pip install neurokit2
import neurokit2 as nk

import seaborn as sns

import pandas as pd
import numpy as np
import time
!pip install mne
import mne

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
data1  = pd.read_csv("/content/drive/My Drive/normalized.csv")

In [ ]:
data2 = data1
data2

Unnamed: 0  Electrode1_1  Electrode1_2  ...  class  valencehigh  arousalhigh
0             0      0.711454      0.816407  ...      3            1            1
1             1      0.720999      0.824642  ...      0            1            1
2             2      0.716593      0.817322  ...      0            1            1
3             3      0.720999      0.828911  ...      1            1            1
4             4      0.721733      0.825557  ...      0            1            1
..          ...           ...           ...  ...    ...          ...          ...
409         409      0.701664      0.804514  ...      1            0            0
410         410      0.713656      0.814578  ...      1            0            0
411         411      0.701175      0.803599  ...      0            1            1
412         412      0.713656      0.817322  ...      2            0            0
413         413      0.721488      0.825252  ...      0            0            1

[414 rows x 107533 columns]

In [ ]:
data2 = data2.drop(['Unnamed: 0'], axis = 1)
data2 = data2.drop(['age'], axis = 1)
data2 = data2.drop(['gender'],axis = 1)
data2 = data2.drop(['video'],axis =1)
data2 = data2.drop(['video_name'],axis =1)
data2 = data2.drop(['target_emotion'],axis =1)
data2 = data2.drop(['valence'],axis =1)
data2 = data2.drop(['arousal'],axis =1)
data2 = data2.drop(['dominance'],axis =1)
data2 = data2.drop(['class'],axis =1)
data2 = data2.drop(['arousalhigh'],axis =1)
data2 = data2.drop(['participant'],axis =1)
data2

Electrode1_1  Electrode1_2  ...  Electrode14_7680  valencehigh
0        0.711454      0.816407  ...          0.276508            1
1        0.720999      0.824642  ...          0.289939            1
2        0.716593      0.817322  ...          0.233153            1
3        0.720999      0.828911  ...          0.288289            1
4        0.721733      0.825557  ...          0.278040            1
..            ...           ...  ...               ...          ...
409      0.701664      0.804514  ...          0.293709            0
410      0.713656      0.814578  ...          0.295123            0
411      0.701175      0.803599  ...          0.288761            1
412      0.713656      0.817322  ...          0.287347            0
413      0.721488      0.825252  ...          0.281221            0

[414 rows x 107521 columns]

In [ ]:
#Data prep for valence
#Valence is judged by alphas of F3 and F4
#F3 is electrode 3, F4 is elctrode 12

#F3 
target=data2['valencehigh']
target

0      1
1      1
2      1
3      1
4      1
      ..
409    0
410    0
411    1
412    0
413    0
Name: valencehigh, Length: 414, dtype: int64

In [ ]:
from sklearn import preprocessing

target
target = preprocessing.scale(target)
target

array([ 0.79772404,  0.79772404,  0.79772404,  0.79772404,  0.79772404,
       -1.25356634,  0.79772404, -1.25356634, -1.25356634,  0.79772404,
        0.79772404,  0.79772404,  0.79772404,  0.79772404, -1.25356634,
        0.79772404, -1.25356634,  0.79772404,  0.79772404, -1.25356634,
        0.79772404, -1.25356634, -1.25356634, -1.25356634,  0.79772404,
       -1.25356634, -1.25356634, -1.25356634,  0.79772404,  0.79772404,
        0.79772404, -1.25356634, -1.25356634, -1.25356634, -1.25356634,
        0.79772404,  0.79772404,  0.79772404,  0.79772404, -1.25356634,
        0.79772404,  0.79772404,  0.79772404, -1.25356634, -1.25356634,
        0.79772404,  0.79772404,  0.79772404,  0.79772404,  0.79772404,
        0.79772404,  0.79772404, -1.25356634,  0.79772404,  0.79772404,
        0.79772404,  0.79772404, -1.25356634,  0.79772404,  0.79772404,
        0.79772404, -1.25356634, -1.25356634, -1.25356634,  0.79772404,
        0.79772404,  0.79772404, -1.25356634, -1.25356634,  0.79

In [ ]:
coll =[]
for i in range(1,7681):
  for j in range(1,15):
    coll.append('Electrode' + str(j) +'_' + str(i) )
    
coll

['Electrode1_1',
 'Electrode2_1',
 'Electrode3_1',
 'Electrode4_1',
 'Electrode5_1',
 'Electrode6_1',
 'Electrode7_1',
 'Electrode8_1',
 'Electrode9_1',
 'Electrode10_1',
 'Electrode11_1',
 'Electrode12_1',
 'Electrode13_1',
 'Electrode14_1',
 'Electrode1_2',
 'Electrode2_2',
 'Electrode3_2',
 'Electrode4_2',
 'Electrode5_2',
 'Electrode6_2',
 'Electrode7_2',
 'Electrode8_2',
 'Electrode9_2',
 'Electrode10_2',
 'Electrode11_2',
 'Electrode12_2',
 'Electrode13_2',
 'Electrode14_2',
 'Electrode1_3',
 'Electrode2_3',
 'Electrode3_3',
 'Electrode4_3',
 'Electrode5_3',
 'Electrode6_3',
 'Electrode7_3',
 'Electrode8_3',
 'Electrode9_3',
 'Electrode10_3',
 'Electrode11_3',
 'Electrode12_3',
 'Electrode13_3',
 'Electrode14_3',
 'Electrode1_4',
 'Electrode2_4',
 'Electrode3_4',
 'Electrode4_4',
 'Electrode5_4',
 'Electrode6_4',
 'Electrode7_4',
 'Electrode8_4',
 'Electrode9_4',
 'Electrode10_4',
 'Electrode11_4',
 'Electrode12_4',
 'Electrode13_4',
 'Electrode14_4',
 'Electrode1_5',
 'Electrode

In [ ]:
data3 = data2[coll]

In [ ]:
data3

Electrode1_1  Electrode2_1  ...  Electrode13_7680  Electrode14_7680
0        0.711454      0.614954  ...          0.195442          0.276508
1        0.720999      0.624939  ...          0.199738          0.289939
2        0.716593      0.621529  ...          0.150817          0.233153
3        0.720999      0.628105  ...          0.193533          0.288289
4        0.721733      0.628349  ...          0.184465          0.278040
..            ...           ...  ...               ...               ...
409      0.701664      0.615928  ...          0.194010          0.293709
410      0.713656      0.628592  ...          0.193533          0.295123
411      0.701175      0.609109  ...          0.198425          0.288761
412      0.713656      0.619094  ...          0.196993          0.287347
413      0.721488      0.631515  ...          0.199260          0.281221

[414 rows x 107520 columns]

In [ ]:
#Data prep to feed into LTSM
# 414 X 12 X (640*14) 
# 414 rows X 12 time frames X 4(theta, alpha, beta, gamma) 
data4 = np.array(data3)
def dataprep(df):
	x = []
	a = []
	q=[]
	row = 0
	while(row<414):
		column =0
		for timestep in range(0,12):
			z=[]
			for i in range(0,640):
				j=14
				y=[]
				while(j):
					a=df[row][column]
					y.append(a)
					column+=1
					j=j-1
				z.append(y)
			q.append(z)
		
		row+=1
		x.append(q)
		q=[]
	return x

dfq = dataprep(data4)
dfq = np.array(dfq)
#dfq = dfq.reshape(dfq[2].shape,dfq[0].shape, dfq[1].shape )
dfq.shape

(414, 12, 640, 14)

In [ ]:
dfa = dfq.reshape(dfq.shape[0],dfq.shape[1], 8960)
dfa.shape

(414, 12, 8960)

In [ ]:
#from keras.utils import to_categorical
#target = to_categorical(target)
target=data2['valencehigh']
target

0      1
1      1
2      1
3      1
4      1
      ..
409    0
410    0
411    1
412    0
413    0
Name: valencehigh, Length: 414, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

target = np.array(target, dtype = float)
x_Train, x_Test, y_Train, y_Test = train_test_split(dfa, target, test_size = 0.25, random_state = 5)
x_Train.shape

(310, 12, 8960)

In [ ]:
x_Test[0]

array([[0.71096427, 0.61714564, 0.62971114, ..., 0.55030684, 0.37762676,
        0.5580512 ],
       [0.59859576, 0.53657393, 0.59833472, ..., 0.70221328, 0.75323899,
        0.70155502],
       [0.42000835, 0.3596949 , 0.27267653, ..., 0.52728651, 0.25897003,
        0.31189189],
       ...,
       [0.65268456, 0.52344666, 0.58311651, ..., 0.71119029, 0.68928879,
        0.67368015],
       [0.59988442, 0.53785851, 0.77038363, ..., 0.51900716, 0.34219755,
        0.23975738],
       [0.33025005, 0.29985476, 0.57702764, ..., 0.57709865, 0.19687388,
        0.2737983 ]])

In [ ]:

#x_Train = x_Train.reshape(x_Train.shape[0],1,48)
#x_Test = x_Test.reshape(x_Test.shape[0],1,48)
#x_Train.shape

In [ ]:
model = Sequential()
model.add(LSTM(64, batch_input_shape=(None,12,8960),activation="relu",return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(32, batch_input_shape=(None,12,8960),activation="sigmoid",return_sequences=False))
model.add(Dropout(0.2))
#model.add(Dense(128, activation='relu'))
model.add(Dense(16, activation= 'sigmoid'))
model.add(Dense(3, activation= 'softmax'))
#model.add(Dense(16))
model.compile(loss = 'sparse_categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
model.summary()

Model: "sequential_15"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_30 (LSTM)               (None, 12, 64)            2310400   
_________________________________________________________________
dropout_15 (Dropout)         (None, 12, 64)            0         
_________________________________________________________________
lstm_31 (LSTM)               (None, 32)                12416     
_________________________________________________________________
dropout_16 (Dropout)         (None, 32)                0         
_________________________________________________________________
dense_35 (Dense)             (None, 16)                528       
_________________________________________________________________
dense_36 (Dense)             (None, 3)                 51        
Total params: 2,323,395
Trainable params: 2,323,395
Non-trainable params: 0
___________________________________________

In [ ]:
history = model.fit(x_Train, y_Train ,epochs=50, validation_data =(x_Test,y_Test))

Epoch 1/50
10/10 [==============================] - 2s 182ms/step - loss: 0.7755 - accuracy: 0.6000 - val_loss: 0.7376 - val_accuracy: 0.6250
Epoch 2/50
10/10 [==============================] - 1s 136ms/step - loss: 0.7433 - accuracy: 0.6065 - val_loss: 0.7200 - val_accuracy: 0.6250
Epoch 3/50
10/10 [==============================] - 1s 132ms/step - loss: 0.7295 - accuracy: 0.6065 - val_loss: 0.7083 - val_accuracy: 0.6250
Epoch 4/50
10/10 [==============================] - 1s 133ms/step - loss: 0.7125 - accuracy: 0.6065 - val_loss: 0.6996 - val_accuracy: 0.6250
Epoch 5/50
10/10 [==============================] - 1s 135ms/step - loss: 0.7055 - accuracy: 0.6065 - val_loss: 0.6945 - val_accuracy: 0.6250
Epoch 6/50
10/10 [==============================] - 1s 138ms/step - loss: 0.7009 - accuracy: 0.6065 - val_loss: 0.6928 - val_accuracy: 0.6250
Epoch 7/50
10/10 [==============================] - 1s 139ms/step - loss: 0.7037 - accuracy: 0.6065 - val_loss: 0.6844 - val_accuracy: 0.6250
Epoch 

In [ ]:
y_pred = model.predict_on_batch(x_Test)
print(y_pred)

[[0.40733543 0.00966256 0.583002  ]
 [0.40732464 0.00966281 0.5830125 ]
 [0.4073193  0.00966538 0.58301526]
 [0.407363   0.00966219 0.5829748 ]
 [0.40731925 0.00966485 0.58301586]
 [0.4073337  0.00966415 0.58300215]
 [0.40725544 0.00966262 0.58308196]
 [0.4073131  0.00966557 0.5830213 ]
 [0.4073381  0.00966455 0.58299726]
 [0.40732402 0.00966408 0.58301187]
 [0.40733376 0.00966398 0.5830023 ]
 [0.40733325 0.00966343 0.5830033 ]
 [0.4073027  0.00966562 0.58303165]
 [0.4073296  0.00966344 0.5830069 ]
 [0.40738338 0.00966228 0.58295435]
 [0.40732807 0.00966358 0.5830084 ]
 [0.4072723  0.0096677  0.58306   ]
 [0.4073444  0.00966284 0.58299273]
 [0.4072319  0.00966671 0.5831014 ]
 [0.4073846  0.00966164 0.58295375]
 [0.4073224  0.00966381 0.5830138 ]
 [0.4073236  0.00966343 0.58301294]
 [0.40732172 0.00966402 0.5830143 ]
 [0.4073394  0.00966425 0.58299637]
 [0.40731436 0.00966396 0.5830217 ]
 [0.40732598 0.00966456 0.5830095 ]
 [0.4073352  0.00966496 0.5829999 ]
 [0.40733412 0.00966443 0.58

In [ ]:
import seaborn as sns
import numpy as np
plt.plot(y_test.flatten(), marker='.', label='true')
plt.plot(y_pred.flatten(), 'r', label='predicted')
plt.legend()
plt.show()

In [ ]:
from sklearn.metrics import accuracy_score
pred = model.predict(x_Test)
predict_classes = np.argmax(pred,axis=1)
expected_classes = np.argmax(y_Test,axis=1)
print(expected_classes.shape)
print(predict_classes.shape)
correct = accuracy_score(expected_classes,predict_classes)
print(f"Training Accuracy: {correct}")

In [ ]:
model=Sequential()
model.add(LSTM(128,batch_input_shape = (414,12,4),activation = 'relu', return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(64,activation ='relu'))
model.add(Dense(32,activation ='sigmoid'))
model.add(Dense(1,activation ='softmax'))


opt = tf.keras.optimizers.Adam(learning_rate=1e-3, decay=1e-5)
model.compile(loss='sparse_categorical_crossentropy',optimizer =opt,metrics=['accuracy'])
#model.compile(loss='binary_crossentropy',optimizer =opt,metrics=['accuracy'])
history = model.fit(x_Train,y_Train,epochs=50, validation_data =(x_Test,y_Test))
y_pred = model.predict(x_Test)

In [ ]:
print(y_pred)